TASK: Update to Zoom Server-To-Server Apps with OAuth, improve exception handling
code-q-web-factory/CodeQ.ZoomApi pull request #7
Opened 2023-09-19 13:14 UTC by gradinarufelix

This PR switches the package to the new server-to-server OAuth authentication pattern at Zoom. Also, exception handling now happens at top-level in the Eel helper.

2023-09-20 09:30 UTC, krsriq requested changes
A few things I noticed besides the inline comments:

- Some PHP 8 functionality is used here, i.e. the package required implicitly PHP 8. But this is not stated in the composer.json (nor in the README).
- Unit tests would be nice here - I imagine it would be relatively easy to test this service class (including the settings and client).
- Links to the api docs should be updated (e.g. for meetings https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetings)
- All kinds of @throws are missing in the DocBlocks - so it is not obvious to method consumers that an exception can be thrown (e.g. in `getUpcomingMeetings`, `getRecordings` and `getAccessToken`).

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +        if(!$zoomApiAccountId || !$zoomApiClientId || !$zoomApiClientSecret) {
Here there is no space after the 'if' - you should let the linter fix at least the changes of this PR..

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +        /** @var array $upcomingMeetings */
If `$upcomingMeetings` can no longer be `bool`, how can it be `=== false`?

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +        /** @var array $upcomingMeetings */
I find the oneliner a bit difficult to read. The solution would be either `$upcomingMeetings = $this->requestsCache->get($cacheEntryIdentifier)` in its own line, or even the entire if condition in its own method (then you would also save yourself the @var type declaration).

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
>          } catch (CacheException $e) {
Can only a `CacheException` be thrown here? What about other throwables?
At least I would log the exception here if one occurs - and maybe put the comment directly in the log message.

```php
         try {
             $this->requestsCache->set($cacheEntryIdentifier, $upcomingMeetings);
         } catch (CacheException $exception) {
             // If CacheException is thrown we just go on and fetch the items directly from Zoom
             // TODO: Somehow log $exception->getMessage(), $exception->getTraceAsString(), ...
         } catch (\Throwable $throwable) {
             // TODO: Somehow log $throwable->getMessage(), $throwable->getTraceAsString(), ...
         }
```
Alternatively, `$e` would be an unused variable (and should be removed).

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +        /** @var array $recordings */
see above - one-liner and var type.
Couldn't be `$from` and `$to` instead of `mixed` union type `DateTime|string` in PHP 8 (as you did in [ZoomApiHelper](https://github.com/code-q-web- factory/CodeQ.ZoomApi/pull/7/files#diff-5fef4db96d6ded0bc3652bb7c734a6cc6f00c7c43fa64a3652c4e8aa51081a33R38)?

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +        if ($bodyContents === "") {
In which case can the content be an empty string? Wouldn't Guzzle throw a `BadResponseException` anyway in that case (presumably 40X)?
Didn't find anything about this in the [Zoom API doc](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetings) - it looks like at least the pagination and a (possibly empty) meetings array are present.

2023-09-20 09:30 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +            throw new Exception('Could not fetch Zoom access token. Please check the settings for account ID, client ID and client secret, as well as your Zoom app.', 1695040346621);
`@throws` is missing from DocBlock

2023-09-20 09:30 UTC, krsriq commented on Classes/Eel/ZoomApiHelper.php
> +            $this->systemLogger->error(sprintf('Could not get Zoom recordings, exception with code "%s" thrown: "%s"', $e->getCode(), $e->getMessage()), LogEnvironment::fromMethodName(__METHOD__));
Maybe it also makes sense to log a stack trace with `$e->getTraceAsString()`?

2023-09-20 09:30 UTC, krsriq commented on Classes/Eel/ZoomApiHelper.php
> +     * @return array|false
It would be nice to describe here in which case `false` can be returned (then this is also clear at first glance in the quick function definition).

2023-09-20 09:30 UTC, krsriq commented on Classes/Eel/ZoomApiHelper.php
> +    public function getUpcomingMeetings(): array|false
see above

2023-09-20 09:30 UTC, krsriq commented on Classes/Eel/ZoomApiHelper.php
> +            $this->systemLogger->error(sprintf('Could not get upcoming Zoom meetings, exception with code "%s" thrown: "%s"', $e->getCode(), $e->getMessage()), LogEnvironment::fromMethodName(__METHOD
see above

2023-09-20 19:39 UTC, gradinarufelix commented on Classes/Domain/Service/ZoomApiService.php
> +        /** @var array $upcomingMeetings */
I extracted this into a separate method. The `VariableFrontend` of Neos caching returns `false` if a cache entry is not found.

2023-09-20 19:44 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +        /** @var array $upcomingMeetings */
So `$upcomingMeetings` may be `false`? Then this `@var` comment declaration change is wrong..

2023-09-20 19:44 UTC, gradinarufelix commented on Classes/Domain/Service/ZoomApiService.php
>          } catch (CacheException $e) {
`$this->requestsCache->set()` only throws `\Neos\Cache\Exception` and `InvalidArgumentException`. However, the latter can only happen if the cache entry identifier or a cache entry tag does not meet the allowed pattern. As we are controlling the cache entry identifier here and are using no tags, the latter exception realistically cannot happen.

2023-09-20 20:07 UTC, gradinarufelix commented on Classes/Domain/Service/ZoomApiService.php
> +        if ($bodyContents === "") {
I don't understand why I put this there. I removed it now.

2023-09-20 20:07 UTC, gradinarufelix commented on Classes/Domain/Service/ZoomApiService.php
> +        /** @var array $recordings */
I now required php 8 and switched to the new notation.

2023-09-21 06:16 UTC, krsriq requested changes
I like how you added a custom ZoomApiException now! Only thing left is to add it to the DocBlock in some places, then I think we're done here!

For this review - especially to see what was up with the empty response and kind of in preparation for our testing meeting next week - I've [hacked together a quick unit test class](https://gist.github.com/krsriq/2eb5bec93c00cdaa5643ce28e7bb4323) for this service class. I'm pretty sure that if we worked on this a bit more we could find some smaller hidden bugs here and there, but I think all in all this looks good now.

2023-09-21 06:16 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +     * @throws GuzzleException
This may also throw an `\Exception` (in case `DateTimeImmutable` fails to parse the string).

2023-09-21 06:16 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +     * @throws GuzzleException
This may also throw a `\CodeQ\ZoomApi\ZoomApiException` now.

2023-09-21 06:16 UTC, krsriq commented on Classes/Domain/Service/ZoomApiService.php
> +     * @throws GuzzleException
This may also throw a `\CodeQ\ZoomApi\ZoomApiException` now.

2023-09-21 11:14 UTC, krsriq approved these changes

2023-09-21 14:58 UTC, merged